"""
Anchor - History Extraction Layer.

This module converts an accountability briefing generated by ChatGPT or Claude into a structured JSON object that can be consumed by the Anchor backend. 
Supported input: 
- Raw pasted text 
- Markdown (.md) 
- Text (.txt) 
- JSON (.json) 

Processing flow:

 Input 

    -> Load content 
    -> Extract structured patterns using Groq 
    -> Validate/normalize the response 
    -> Prepare backend payload 
    -> POST /users/:id/patterns
    
     """
import json
import os

import requests
from pathlib import Path
from groq import Groq
from dotenv import load_dotenv

load_dotenv()


# ---------------------------------------------------------------------------
# 1. Extraction System Prompt
# ---------------------------------------------------------------------------

EXTRACTION_SYSTEM_PROMPT = """
You are an expert data extraction agent for an accountability application
called Anchor.

Your task is to analyze the user's input. The input may be:
- Raw text
- Markdown
- JSON
- An accountability briefing generated by ChatGPT or Claude

Extract facts directly from the input and return ONLY a valid JSON object.

IMPORTANT RULES:
1. Do not invent, infer, or assume facts.
2. Preserve the meaning of the original input.
3. If information is not present, use an empty array [] or empty string "".
4. Do not add markdown code fences.
5. Do not add explanations before or after the JSON.
6. Keep current_projects as a simple list of project names.
7. Keep priorities as clear, concise priority statements.
8. Keep habits as concrete recurring habits or routines.
9. personality.drivers should contain motivations or behavioral drivers.
10. personality.risk should contain the main behavioral risk pattern.
11. working_style should summarize how the person tends to work.
12. baseline_load should summarize the person's current workload/capacity.
13. pitfalls should contain recurring mistakes, avoidance behaviors,
    overcommitment patterns, or other accountability risks.
14. raw_import must contain the complete original input exactly as provided.

Return JSON in exactly this structure:

{
  "source": "chatgpt",
  "personality": {
    "drivers": [],
    "risk": ""
  },
  "pitfalls": [],
  "working_style": "",
  "current_projects": [],
  "baseline_load": "",
  "priorities": [],
  "habits": [],
  "raw_import": ""
}
"""


# ---------------------------------------------------------------------------
# 2. Load Input
# ---------------------------------------------------------------------------

def load_file_content(file_path_or_text: str) -> str:
    """
    Accept either:
    - raw pasted text
    - a path to .md, .txt, or .json file
    """

    path = Path(file_path_or_text)

    if path.is_file():
        with open(path, "r", encoding="utf-8") as file:
            return file.read()

    return file_path_or_text


# ---------------------------------------------------------------------------
# 3. Extract History Using Groq
# ---------------------------------------------------------------------------

def extract_history_to_patterns(raw_input: str) -> dict:
    """
    Extract accountability patterns from ChatGPT/Claude history
    into Anchor's patterns schema.
    """

    content = load_file_content(raw_input)

    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        raise ValueError(
            "GROQ_API_KEY environment variable is not set."
        )

    client = Groq(api_key=api_key)

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        temperature=0.0,
        messages=[
            {
                "role": "system",
                "content": EXTRACTION_SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": (
                    "Extract the accountability patterns from the "
                    "following ChatGPT/Claude history:\n\n"
                    f"{content}"
                ),
            },
        ],
    )

    response_text = response.choices[0].message.content.strip()

    # Remove accidental markdown code fences
    if response_text.startswith("```"):
        lines = response_text.splitlines()

        # Remove first line (```json / ```)
        lines = lines[1:]

        # Remove final ```
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]

        response_text = "\n".join(lines).strip()

    try:
        normalized_data = json.loads(response_text)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Groq returned invalid JSON:\n{response_text}"
        ) from exc

    # Make absolutely sure raw_import contains the original input.
    normalized_data["raw_import"] = content

    return normalized_data


# ---------------------------------------------------------------------------
# 4. Validate / Normalize Output
# ---------------------------------------------------------------------------

def ensure_patterns_schema(data: dict) -> dict:
    """
    Ensure the extracted data follows Anchor's expected schema.
    """

    personality = data.get("personality") or {}

    return {
        "source": data.get("source", "chatgpt"),
        "personality": {
            "drivers": personality.get("drivers", []),
            "risk": personality.get("risk", ""),
        },
        "pitfalls": data.get("pitfalls", []),
        "working_style": data.get("working_style", ""),
        "current_projects": data.get("current_projects", []),
        "baseline_load": data.get("baseline_load", ""),
        "priorities": data.get("priorities", []),
        "habits": data.get("habits", []),
        "raw_import": data.get("raw_import", ""),
    }


# ---------------------------------------------------------------------------
# 5. Backend API Adapter
# ---------------------------------------------------------------------------

def map_to_backend_payload(
    normalized_data: dict,
    user_id: str,
) -> dict:
    """
    Create the exact payload expected by:

        POST /users/:id/patterns
    """

    patterns = ensure_patterns_schema(normalized_data)

    return {
        "user_id": user_id,
        **patterns,
    }

# ---------------------------------------------------------------------------
# 6. POST function to backend
# ---------------------------------------------------------------------------



def post_patterns_to_backend(
    user_id: str,
    patterns: dict,
    backend_url: str,
) -> dict:
    """
    POST extracted accountability patterns to Anchor backend.
    """

    url = f"{backend_url}/users/{user_id}/patterns"

    response = requests.post(
        url,
        json=patterns,
        timeout=30,
    )

    response.raise_for_status()

    return response.json()



if __name__ == "__main__":

    briefing_file_path = "Accountability Coach Briefing — Mary Sophiya.md"

    try:
        print("Starting extraction layer with Groq...")

        # ---------------------------------------------------------------
        # Step 1: Read ChatGPT/Claude export
        # ---------------------------------------------------------------

        normalized_data = extract_history_to_patterns(
            briefing_file_path
        )

        print("\n--- Extracted Patterns ---")

        print(
            json.dumps(
                normalized_data,
                indent=2,
                ensure_ascii=False,
            )
        )

        # ---------------------------------------------------------------
        # Step 2: Create backend payload
        # ---------------------------------------------------------------

        user_id = "user_12345"

        backend_payload = map_to_backend_payload(
            normalized_data,
            user_id=user_id,
        )

        print("\n--- Final Backend Payload ---")

        print(
            json.dumps(
                backend_payload,
                indent=2,
                ensure_ascii=False,
            )
        )

        result = post_patterns_to_backend(
            user_id="user_12345",
            patterns=backend_payload,
            backend_url="http://localhost:8000",
        )

        print("\n--- Backend Response ---")
        print(json.dumps(result, indent=2))

    except FileNotFoundError:
        print(
            f"Error: Could not find file at "
            f"'{briefing_file_path}'"
        )

    except Exception as exc:
        print(
            f"An error occurred during execution: {exc}"
        )